version: '3.8'

networks:
    laravel-network:
        driver: bridge

services:
    mysql:
        image: mysql:latest
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 5s
            timeout: 2s
            retries: 3
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456789
            MYSQL_DATABASE: laravel
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel-network

    laravel-app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: 123456789
            NEWS_API_KEY: 537c16dc0afc4ea7a5fa8ceec14e345a
            NYTIMES_API_KEY: hgSUAB7U43TAAZUVCEauSGURyUTuvL7y
            GUARDIAN_API_KEY: 27b4c167-6788-4995-95a1-72770336d6d2
            NEWS_API_URL: https://newsapi.org/v2/top-headlines
            NYTIMES_API_URL: https://api.nytimes.com/svc/topstories/v2/home.json
            GUARDIAN_API_URL: https://content.guardianapis.com/search
        command: bash -c "php artisan install-command && php-fpm"
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - laravel-network

    nginx:
        image: nginx:latest
        ports:
            - "9000:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - laravel-app
        networks:
            - laravel-network

volumes:
    mysql_data:
